export const FETCHING_MONUMENTS = 'FETCHING_MONUMENTS';

export const FETCHING_IMAGE_RECOGNITION = 'FETCHING_IMAGE_RECOGNITION';

export const FETCHING_GET_USER_SESSION = 'FETCHING_GET_USER_SESSION'

export const GET_CURRENT_LOCATION_PENDING = 'GET_CURRENT_LOCATION_PENDING';
export const GET_CURRENT_LOCATION_FULFILLED = 'GET_CURRENT_LOCATION_FULFILLED';
export const GET_CURRENT_LOCATION_REJECTED = 'GET_CURRENT_LOCATION_REJECTED';


export const _PENDING = '_PENDING';
export const _FULFILLED = '_FULFILLED'
export const _REJECTED = '_REJECTED'